# Site settings
title: Ben Wilber
email: benwilber@gmail.com
description: >
  Ben Wilber on the Arts and Crafts of programming, 
  systems, automation, and other less useful things.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://benwilber.github.io"
twitter_username: benwilber
github_username:  benwilber

# Build settings
markdown: kramdown
kramdown:
  input: GFM
